name: Pigeons and Pates
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9198222376871854
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070705'
    - '#fffaec'
    - '#77694e'
    - '#e1cba2'
    - '#363a2b'
  brandStrength: 0.7933055509347469
  lightness: 0.3085586435627192
  saturation: 0.3183159059844911
  rhythmicContrast: 0.6304267423693091
purpose: []
